feat: support auto use latest version

diff --git a/core b/core
--- a/core
+++ b/core
@@ -14,6 +14,16 @@ install() {
   local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
   local tmp_dir="$PACKAGE_TMP_DIR"
 
+  # get latest version
+  log::info "[$(timestamp)][package][$name] checking latest version ..."
+  local latest_version=$(git::get_remote_latest_tag $PACKAGE_CORE_GIT_REPOSITORY)
+  if [ "$?" != "0" ]; then
+    log::error "[$(timestamp)][package][$name] failed to get latest version ."
+    return 1
+  fi
+  PACKAGE_CORE_VERSION=$latest_version
+  log::success "[$(timestamp)][package][$name] latest version: $PACKAGE_CORE_VERSION"
+
   # files
   local tmp_file="$name.tar.gz"
   local bin_file="./$name"
@@ -39,7 +49,7 @@ install() {
   log::info "[$(timestamp)][package][$name] extracting ..."
   os::extract $tmp_file
 
-   # install
+  # install
   log::info "[$(timestamp)][package][$name] installing ..."
   os::install $bin_file $usr_bin_dir
 
